server:
  port: 8080

spring:
  datasource:
    # url: jdbc:mariadb://6fb21019-440b-4ad8-b69e-d9adc45c2c9b.internal.kr1.mariadb.rds.nhncloudservice.com:3306/UsersService
    url: msa-mariadb-rds20250721022536253700000001.cxca0yecyzdl.ap-northeast-2.rds.amazonaws.com
    username: MSA_User
    password: P@ssw0rd
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
